#!/usr/bin/env bash
# publish-obsidian.sh — Publish a markdown file into an Obsidian vault note, reliably.
#
# Why this exists: writing into a OneDrive-synced vault over WSL's /mnt/c (9p + Files-On-Demand)
# is flaky with editor/agent file tools — files can land in the wrong folder. Plain bash `cp`
# works, so this script does the write via cp and then VERIFIES the result (size match), retrying
# once. It also warns about duplicate note names (Obsidian resolves obsidian:// URIs by basename).
#
# This is the fallback backend for the `to-obsidian` skill. When the Obsidian MCP server is
# available (see SETUP.md), the skill should prefer the MCP tools instead and skip this script.
#
# Usage:
#   publish-obsidian.sh --vault <name|abs-path> --note <relative/note.md> --source <file.md> [--force]
#     --vault   Obsidian vault NAME (resolved via obsidian.json) or an absolute vault path
#     --note    Note path relative to the vault root, e.g. "전체적인 코드 분석.md"
#     --source  Adapted markdown file whose content becomes the note (skill prepares this)
#     --force   Overwrite even if the target has content NOT generated by this skill
#
# Exit codes: 0 ok | 2 bad args | 3 vault not resolved | 4 refused (foreign content) | 5 write failed
set -euo pipefail

VAULT=""; NOTE=""; SOURCE=""; FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --vault)  VAULT="${2:-}"; shift 2;;
    --note)   NOTE="${2:-}"; shift 2;;
    --source) SOURCE="${2:-}"; shift 2;;
    --force)  FORCE=1; shift;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done
[[ -n "$VAULT" && -n "$NOTE" && -n "$SOURCE" ]] || { echo "missing required args (--vault --note --source)" >&2; exit 2; }
[[ -f "$SOURCE" ]] || { echo "source not found: $SOURCE" >&2; exit 2; }

# --- resolve vault name -> WSL path via obsidian.json (or accept an absolute path) ---
resolve_vault() {
  local v="$1"
  if [[ "$v" == /* ]]; then printf '%s' "$v"; return 0; fi
  python3 - "$v" <<'PY'
import glob, json, os, re, sys
name = sys.argv[1]
candidates = glob.glob("/mnt/c/Users/*/AppData/Roaming/obsidian/obsidian.json")
candidates += glob.glob("/mnt/*/Users/*/AppData/Roaming/obsidian/obsidian.json")
home_cfg = os.path.expanduser("~/.config/obsidian/obsidian.json")
if os.path.exists(home_cfg):
    candidates.append(home_cfg)
def win_to_wsl(p):
    m = re.match(r'^([A-Za-z]):[\\/](.*)$', p)
    if m:
        return f"/mnt/{m.group(1).lower()}/" + m.group(2).replace('\\', '/')
    return p
for cfg in candidates:
    try:
        d = json.load(open(cfg, encoding='utf-8'))
    except Exception:
        continue
    for info in (d.get('vaults') or {}).values():
        p = info.get('path', '')
        base = os.path.basename(p.replace('\\', '/').rstrip('/'))
        if base == name:
            print(win_to_wsl(p)); sys.exit(0)
sys.exit(3)
PY
}
VAULT_PATH="$(resolve_vault "$VAULT")" || { echo "could not resolve vault '$VAULT' (not an abs path, not found in obsidian.json)" >&2; exit 3; }
[[ -d "$VAULT_PATH" ]] || { echo "resolved vault path does not exist: $VAULT_PATH" >&2; exit 3; }

TARGET="$VAULT_PATH/$NOTE"
mkdir -p "$(dirname "$TARGET")"

# --- safety: don't clobber content we didn't generate ---
if [[ -s "$TARGET" && $FORCE -eq 0 ]]; then
  if ! grep -q 'generated-by: to-obsidian' "$TARGET" 2>/dev/null; then
    echo "REFUSED: '$TARGET' already has content not generated by this skill." >&2
    echo "         Re-run with --force to overwrite, or pick a different --note." >&2
    exit 4
  fi
fi

# --- duplicate note-name warning (Obsidian resolves obsidian:// by basename) ---
base="$(basename "$NOTE")"
dups="$(find "$VAULT_PATH" -name "$base" -not -path "$TARGET" 2>/dev/null || true)"
[[ -n "$dups" ]] && { echo "WARNING: other notes named '$base' exist — obsidian:// URI may be ambiguous:" >&2; echo "$dups" >&2; }

# --- write via cp + verify (+ one retry) to defeat the /mnt/c OneDrive/9p quirk ---
src_bytes="$(wc -c <"$SOURCE")"
write_and_verify() {
  cp -f "$SOURCE" "$TARGET" 2>/dev/null || return 1
  sync 2>/dev/null || true
  [[ -f "$TARGET" ]] || return 1
  [[ "$(wc -c <"$TARGET")" -eq "$src_bytes" ]] || return 1
  return 0
}
if ! write_and_verify; then
  sleep 1
  write_and_verify || { echo "FAILED: target missing or size mismatch after write: $TARGET" >&2; exit 5; }
fi

echo "PUBLISHED: $TARGET ($(wc -c <"$TARGET") bytes)"
